# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 32

###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk_multiscan" #  #  # "SemKITTI_sk" #
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/sematickitti/semantic-kitti_ssl_teacher_student.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4

###################
## Data_loader options
train_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/semantic-kitti/train_pseudo_60/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 4 #4
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/semantic-kitti/train_pseudo_60/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 0
  
test_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/semantic-kitti/train_pseudo_60/sequences"
  imageset: "test"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 4

ssl_data_loader:
  data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/semantic-kitti/train_pseudo_60/sequences"
  imageset: "pseudo"
  return_ref: True
  batch_size: 4
  shuffle: False
  num_workers: 4

###################
## test params
train_params:
  model_load_path: "./model_save_dir/model_save_f1_1_s60_b4_t1.pt"
  model_save_path: "./model_save_dir/model_save_f1_1_s60_b4_t1.pt"
  checkpoint_every_n_steps: 1000
  max_num_epochs: 40
  eval_every_n_steps: 1000
  learning_rate: 0.001
  past: 1
  future: 1
  T_past: 1
  T_future: 11
  ssl: False
  rgb: False
